/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoSolicitarRouteImport } from './routes/como-solicitar'
import { Route as ClinicasRouteImport } from './routes/clinicas'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoSolicitarRoute = ComoSolicitarRouteImport.update({
  id: '/como-solicitar',
  path: '/como-solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasRoute = ClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
  '/como-solicitar': typeof ComoSolicitarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
  '/como-solicitar': typeof ComoSolicitarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
  '/como-solicitar': typeof ComoSolicitarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinicas'
    | '/como-solicitar'
    | '/contato'
    | '/faq'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinicas' | '/como-solicitar' | '/contato' | '/faq' | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/clinicas'
    | '/como-solicitar'
    | '/contato'
    | '/faq'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicasRoute: typeof ClinicasRoute
  ComoSolicitarRoute: typeof ComoSolicitarRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-solicitar': {
      id: '/como-solicitar'
      path: '/como-solicitar'
      fullPath: '/como-solicitar'
      preLoaderRoute: typeof ComoSolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas': {
      id: '/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof ClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicasRoute: ClinicasRoute,
  ComoSolicitarRoute: ComoSolicitarRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
